[package]
authors = ["Zack Smith <zack.smith@motorolasolutions.com>"]
name = "rust-flip"
version = "1.0.0"
description = "Flips a coin `n` times with optional results for heads and tails"

[dependencies]
clap = "2.19.2"
rand = "0.3.15"
